language: python
python:
  - "3.11"

dist: focal
os: linux

install:
  - pip install -r requirements.txt
script:
  - black --check .
  - flake8 .
  - coverage run --source=assignment_1,polls manage.py test polls
  - coverage report
  - coverage xml
after_success:
  - echo $TRAVIS_JOB_ID
  - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN coveralls --verbose

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-poll"
  bucket: $AWS_S3_BUCKET
  bucket_path: "django-poll"
  cleanup: false
  on:
    branch: main
