language: python
python:
  - "3.11"

install:
  - pip install -r requirements.txt

script:
  - pytest

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-poll"
  bucket_name: $AWS_S3_BUCKET
  bucket_path: "django-poll"
  skip_cleanup: true
  on:
    branch: main
